#%RAML 1.0
---
title: Customer Management API
baseUri: http://customermanagement.prasantha.api.com.au/resource/customerservice
version: v1
mediaType: application/json

types:
  If-Modified-Since:
    type: datetime
    example: Sun, 08 Oct 2017 00:00:00 GMT
    format: rfc2616 # this time it's required as otherwise the example is in an invalid format
  customer: !include customer.schema


traits:
  pageable:
    queryParameters:
      offset:
        description: Skip over a number of elements by specifying an offset value for the query
        type: integer
        required: false
        example: 20
        default: 0
      limit:
        description: Limit the number of elements on the response
        type: integer
        required: false
        example: 80
        default: 10

/customers:
  /list:
    get:
      headers:
        If-Modified-Since:
          description: Return the object only if it has been modified since the specified time, otherwise return a 304 (not modified).
      is: [pageable]
      description: List All Customers
      queryParameters:
        If-Modified-Since:
          displayName: Retrieve from modified date
          type: datetime
          description: Retrieve customer where modified date is > passed in value
          example: Sun, 08 Oct 2017 00:00:00 GMT
          format: rfc2616 # this time it's required as otherwise the example is in an invalid format
          required: false
      responses:
        200:
          headers:
            If-Modified-Since:
              type: datetime
              example: Sun, 08 Oct 2017 00:00:00 GMT
              format: rfc2616 # this time it's required as otherwise the example is in an invalid format
          body:
            application/json:
              type: array
              example: !include customers.sample

  /{customerId}:
    get:
      description: Retrieve customer by id
      responses:
        200:
          body:
            application/json:
              type: customer
              example: !include customer.sample
        404:
          body:
            application/json:
              example: |
                {"message": "Resource/Customer not found" }
    put:
      description: Update the customer if found, otherwise return Not found status code and error message
      body:
        application/json:
          example: !include customer.sample
      responses:
        200:
          body:
            application/json:
              example: !include customer.sample
        404:
          body:
            application/json:
              example: |
                {"message": "Resource/Customer not found" }
    delete:
       description: Delete the Customer by customerId
       responses:
         204:
           description: Customer deletion is successful. No Content
         404:
           description: Resource/Customer Not found

    #Extension
    /orders:
      /{orderId} :
        get:
          description: Retrieve Order of the Customer
        /products :
          /{productId} :
            get:
              description: Retrieve Products

  post:
    description: Create a new customer and return newly created customer's resource location
    body:
      application/json:
        example: !include customer.sample
    responses:
      201:
        headers:
          Location:
            type: string
            description: returns created resource location
            example: http://customermanagement.prasantha.api.com.au/resource/customerservice/customers/5
        description: Http Header contains Created Status code and newly created customer's resource location

/orders:
  /{orderId} :
    get:
      description: Retrieve Order of the Customer

/products:
  /{productId} :
    get:
      description: Retrieve Products
